name: Compile and Commit All LaTeX PDFs

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

      - name: Compile all .tex files
        run: |
          find . -name '*.tex' | while read -r texfile; do
            dir=$(dirname "$texfile")
            filename=$(basename "$texfile")
            pdflatex -output-directory "$dir" -interaction=nonstopmode "$texfile"
          done

      - name: Commit and push all PDFs
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git add '**/*.pdf'
          if git diff --cached --quiet; then
            echo "No PDF changes to commit"
            exit 0
          fi
          git commit -m "Auto-compile LaTeX PDFs on push"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.ref_name }}
