name: Compile and Commit All PDFs with pdfLaTeX

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

      - name: Compile all .tex with pdfLaTeX
        shell: bash
        run: |
          set -eo pipefail
          find . -type f -name '*.tex' | while IFS= read -r texfile; do
            dir=$(dirname "$texfile")
            base=$(basename "$texfile")
            echo "::group::Compiling $texfile"
            pdflatex -interaction=nonstopmode -halt-on-error -output-directory "$dir" "$texfile" >"$dir/compile.log" 2>&1 || {
              echo "::error::Compilation failed: $texfile"
              cat "$dir/compile.log"
              exit 1
            }
            echo "::endgroup::"
          done

      - name: Commit and push all PDFs
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git add '**/*.pdf'
          if git diff --cached --quiet; then
            echo "No PDF changes to commit"
            exit 0
          fi
          git commit -m "Auto-compile all LaTeX PDFs with pdfLaTeX"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.ref_name }}
