name: Compile and Commit All PDFs with XeLaTeX

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install TeX Live 2024
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl -sL https://dl.cloudsmith.io/public/latexdevteam/texlive/cfg/setup/key.gpg.key \
            | sudo tee /etc/apt/trusted.gpg.d/texlive.asc >/dev/null
          echo "deb [arch=amd64] https://dl.cloudsmith.io/public/latexdevteam/texlive/debian/ stable main" \
            | sudo tee /etc/apt/sources.list.d/texlive.list
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile all .tex with XeLaTeX and shell escape
        shell: bash
        run: |
          set -eo pipefail
          find . -type f -name '*.tex' | while IFS= read -r texfile; do
            dir=$(dirname "$texfile")
            echo "::group::Compiling $texfile"
            for i in 1 2; do
              xelatex -file-line-error -shell-escape -interaction=nonstopmode -halt-on-error \
                -output-directory "$dir" "$texfile" >>"$dir/compile.log" 2>&1 || {
                echo "::error::Compilation failed: $texfile"
                cat "$dir/compile.log"
                exit 1
              }
            done
            echo "::endgroup::"
          done

      - name: Commit and push all PDFs
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git add '**/*.pdf'
          if git diff --cached --quiet; then
            echo "No PDF changes to commit"
            exit 0
          fi
          git commit -m "Auto-compile LaTeX PDFs with XeLaTeX"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.ref_name }}
